import { FormEvent, SyntheticEvent, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const [name, setName] = useState("");

  const router = useRouter();

  const handleNameChange = (event: FormEvent<HTMLInputElement>) => {
    setName(event.currentTarget.value);
  };

  const handleSubmit = (event: SyntheticEvent) => {
    event.preventDefault();

    // set name in global state
    router.push("/game");
  };

  return (
    <div>
      <Head>
        <title>Project Aldgate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-max mx-auto mt-12 flex flex-col items-center">
        <h1 className="text-blue-600 text-xl">Project Aldgate</h1>

        <form onSubmit={handleSubmit}>
          <label className="flex flex-col gap-2 mt-4">
            Please enter your name
            <input
              type="text"
              value={name}
              onChange={handleNameChange}
              className="text-lg border rounded p-2"
              required
            />
          </label>

          <button type="submit" className="bg-green-500 p-4 rounded mt-4">
            START
          </button>
        </form>
      </main>
    </div>
  );
};

export default Home;
