import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import useInterval from "../hooks/useInterval";

const testString = "AHGFG";

const Home: NextPage = () => {
  const [letterIndex, setLetterIndex] = useState(0);

  useInterval(() => {
    setLetterIndex(letterIndex + 1);
  }, 2000);

  return (
    <div>
      <Head>
        <title>Project Aldgate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="border w-max mx-auto mt-12">
        <h1 className="text-blue-600 text-xl">N-Back task</h1>

        <h2 className="text-xl mt-4">
          Click yes if this letter was same as 2 letters ago:
        </h2>

        <p className="text-5xl mt-4 text-center">{testString[letterIndex]}</p>
      </main>
    </div>
  );
};

export default Home;
